"use client";
import { useState } from "react";
import type { DemoContent } from "@/lib/content-types";
import { ArtifactCard, AtlasDemoShell, LifecycleRail, PageHeading, ScenarioStrip } from "@/components/demo/AtlasDemo";
import { demoScenario } from "@/data/demo/scenario";
const steps=["事件描述","机器人与运行环境","Runtime Dataset / 证据可用性","审核、优先级与分派"];
export default function Tier1DemoClient({content}:{content:DemoContent}) { void content; const [step,setStep]=useState(0); return <AtlasDemoShell role="Tier 1 / 一线支持"><PageHeading eyebrow="REF INTAKE" title="REF 创建与一线受理" description="Tier 1 仅可分类、检查证据并分派；不能确认根因。提交为演示交互，不写入真实后台。"/><ScenarioStrip/><div className="mt-6"><LifecycleRail active={step<2?"Runtime Dataset":"REF"}/></div>
 <div className="mt-6 overflow-x-auto"><ol className="flex min-w-[820px]">{steps.map((s,i)=><li className="flex flex-1 items-center" key={s}><button type="button" onClick={()=>setStep(i)} className={`min-h-11 border px-4 text-left text-[13px] font-semibold ${i===step?"border-[#1667b1] bg-[#e8f3ff] text-[#07579e]":"border-[#ccd8e5] bg-white"}`}>{i+1}. {s}</button>{i<3&&<span className="px-2">→</span>}</li>)}</ol></div>
 <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_.7fr]"><ArtifactCard title={steps[step]} status={step===3?"READY FOR REVIEW":"DRAFT"} boundary="Tier 1 不能确认根因；提交仅模拟分派。">{step===0?<Field label="事件" value={demoScenario.event}/>:step===1?<><Field label="机器人" value={demoScenario.robot}/><Field label="运行环境" value="室内 / 示例科技园区 / Demo Linux 22.04"/></>:step===2?<dl className="grid gap-4 sm:grid-cols-2"><Item k="STATUS" v="Available / Locked"/><Item k="DATASET" v={demoScenario.dataset}/><Item k="SOURCE" v="Atlas Agent / Robot runtime"/><Item k="RETENTION" v="30 days · policy controlled"/><Item k="EVENT TIME" v="2030-01-01 08:15:22 +08:00"/><Item k="EVIDENCE PACK" v={`${demoScenario.evidencePack} · 可生成`}/></dl>:<dl className="grid gap-4 sm:grid-cols-2"><Item k="PRIORITY" v="P2 · Human review"/><Item k="ASSIGNEE" v="Tier 2 OEM Engineering"/><Item k="REF" v={demoScenario.ref}/><Item k="ACTION" v="Classify → evidence check → assign"/></dl>}<div className="mt-5 flex gap-2"><button disabled={step===0} onClick={()=>setStep(x=>x-1)} className="min-h-11 border px-4 disabled:opacity-40">上一步</button><button onClick={()=>step<3?setStep(x=>x+1):undefined} className="min-h-11 bg-[#1667b1] px-4 font-semibold text-white">{step<3?"下一步":"演示提交 / 不写入后台"}</button></div></ArtifactCard><ArtifactCard title="资料完整性" status="REVIEW"><ul className="space-y-3"><li className="text-green-700">● Runtime Dataset 已锁定</li><li className="text-green-700">● 事件时间已提供</li><li className="text-[#8a6500]">▲ 缺少现场网络拓扑附件</li><li className="text-[#8a6500]">▲ 客户复现步骤待补充</li></ul></ArtifactCard></div></AtlasDemoShell> }
function Field({label,value}:{label:string;value:string}){return <label className="mb-4 block text-[11px] font-bold">{label}<textarea className="mt-2 block min-h-20 w-full border border-[#ccd8e5] bg-[#f7f9fc] p-3 text-[13px] font-normal" defaultValue={value}/></label>}; function Item({k,v}:{k:string;v:string}){return <div><dt className="text-[11px] text-[#66798d]">{k}</dt><dd className="mt-1 font-medium">{v}</dd></div>}
