export const glossaryEn = {
  title: "Glossary",
  description: "Core terminology of the Atlas Runtime Governance System",
  categories: {
    core: "Core Concepts",
    workflow: "Workflow",
    technical: "Technical Terms",
  },
  terms: [
    {
      term: "Evidence Pack (EP)",
      chinese: "证据包",
      definition:
        "A standardized runtime evidence package containing sensor data, logs, timeline, root cause analysis suggestions, and organizational history at the time of failure. The Evidence Pack is the core deliverable of the Atlas system for cross-team collaboration and historical reuse.",
      category: "core",
    },
    {
      term: "Runtime Event Fault (REF)",
      chinese: "运行时故障事件",
      definition:
        "An anomalous event detected during robot runtime, such as sensor data loss, timestamp jumps, performance degradation, or data format errors. REF is the starting point that triggers evidence generation.",
      category: "core",
    },
    {
      term: "Runtime Governance Agent (RGA)",
      chinese: "运行时治理代理",
      definition:
        "A lightweight agent program deployed on the robot host, responsible for 24/7 observation of runtime surfaces, anomaly detection, Evidence Pack generation, and evidence submission workflow management.",
      category: "core",
    },
    {
      term: "Runtime Investigation",
      chinese: "运行时调查",
      definition:
        "Atlas product line for robot OEMs, designed to accelerate fault investigation and cross-team collaboration. Compresses traditional 3-5 day investigation cycles to hours and supports historical case reuse.",
      category: "core",
    },
    {
      term: "Runtime Sensor Governance",
      chinese: "运行时传感器治理",
      definition:
        "Atlas product line for sensor manufacturers, designed to proactively monitor sensor health in customer field deployments, detect early failure signs, and assist customers with rapid troubleshooting.",
      category: "core",
    },
    {
      term: "Incident Report (IR)",
      chinese: "事故报告",
      definition:
        "A formal investigation report generated by engineers based on the Evidence Pack, including root cause determination, responsibility attribution, and remediation recommendations. IR is reviewed by humans and archived to the organizational knowledge base.",
      category: "workflow",
    },
    {
      term: "Lesson Learned (LL)",
      chinese: "经验总结",
      definition:
        "Reusable knowledge extracted from historical incidents, including failure patterns, diagnostic methods, and solutions. LL is used to accelerate investigation of similar future issues.",
      category: "workflow",
    },
    {
      term: "Assist Vault",
      chinese: "协助保管库",
      definition:
        "Atlas organizational memory storage system that preserves all historical Evidence Packs, Incident Reports, and Lessons Learned. The Vault supports semantic retrieval to automatically recall similar historical cases.",
      category: "workflow",
    },
    {
      term: "Candidate Timeline",
      chinese: "候选时间线",
      definition:
        "A fault timeline automatically reconstructed by the system based on sensor data, logs, and runtime events. Engineers can quickly locate the failure window based on the Candidate Timeline.",
      category: "workflow",
    },
    {
      term: "Five-Window Constitution",
      chinese: "五窗口宪法",
      definition:
        "The standard structural specification for Atlas Evidence Packs, comprising five dimensions: Sensor Window, Log Window, System Window, Historical Window, and Collaboration Window, ensuring evidence completeness and comparability.",
      category: "technical",
    },
    {
      term: "Evidence Governance Protocol (EGP)",
      chinese: "证据治理协议",
      definition:
        "A standard protocol defining Evidence Pack generation, validation, submission, and archival processes. EGP ensures evidence interoperability across teams and organizations.",
      category: "technical",
    },
    {
      term: "Runtime Surface",
      chinese: "运行时监测维度",
      definition:
        "The target dimensions observed by RGA, including sensor data streams, message buses, power state, network connectivity, storage capacity, etc. Each dimension corresponds to a set of health check rules.",
      category: "technical",
    },
    {
      term: "FAE",
      chinese: "现场应用工程师",
      definition:
        "Field Application Engineer, a technical expert from the sensor manufacturer deployed on-site or providing remote support to customers, responsible for sensor integration, fault diagnosis, and technical training.",
      category: "workflow",
    },
  ],
};
