"use client";
import { useState } from "react";
import type { DemoContent } from "@/lib/content-types";
import { ArtifactCard, AtlasDemoShell, LifecycleRail, PageHeading, ScenarioStrip } from "@/components/demo/AtlasDemo";
import { demoScenario } from "@/data/demo/scenario";

const stages = ["Evidence Pack", "Historical RGA", "Investigation Context", "Tier Candidate", "EGP Preview"];
export default function InvestigationDemoClient({ content }: { content: DemoContent }) {
 void content;
 const [stage,setStage]=useState(stages[0]);
 return <AtlasDemoShell role="Tier 2 / Tier 3 OEM 工程调查"><PageHeading eyebrow="OEM ENGINEERING WORKSPACE" title="运行时证据与工程调查" description="同一 Demo Robotics 案例的 OEM 工程视图；候选、相似性和上下文均需工程师审查。"/><ScenarioStrip/><div className="mt-6"><LifecycleRail active={stage === "Tier Candidate" ? "Investigation Tier" : stage}/></div>
 <nav className="mt-6 flex flex-wrap gap-2" aria-label="调查阶段">{stages.map(s=><button type="button" key={s} onClick={()=>setStage(s)} className={`min-h-11 border px-4 text-[13px] font-semibold ${stage===s?"border-[#1667b1] bg-[#1667b1] text-white":"border-[#ccd8e5] bg-white"}`}>{s}</button>)}</nav>
 <div className="mt-5 grid gap-5 xl:grid-cols-[1.25fr_.75fr]">
 <ArtifactCard title={`${stage} · ${stage==="Evidence Pack"?demoScenario.evidencePack:demoScenario.ref}`} status="HUMAN REVIEW" owner="Li Hua / OEM Engineering" boundary="root_cause_inferred=false · 历史相似性不等于根因确认">
 {stage==="Evidence Pack" ? <><div className="grid min-w-[760px] grid-cols-5 gap-2 overflow-x-auto">{[["Pre-event","08:14:52–08:15:12"],["Near-event","08:15:12–08:15:22"],["Canonical event T0","08:15:22.347"],["Post-event","08:15:27–08:15:32"],["Post-event guard","08:15:32–08:15:52"]].map(([a,b],i)=><div className={`border p-3 ${i===2?"border-[#e1b72c] bg-[#fff7d6]":"border-[#ccd8e5] bg-[#f7f9fc]"}`} key={a}><b>{a}</b><p className="mt-2 font-mono text-[11px]">{b}</p></div>)}</div><p className="mt-4">多来源对齐：ROS Topic · Linux Runtime · Ethernet · Power · Timing</p><p className="mt-2 font-mono">Window Policy · {demoScenario.windowPolicy}</p></> : stage==="Historical RGA" ? <div className="grid gap-3 sm:grid-cols-2">{["Strong Candidate · 87%","Partial Candidate · 64%","Related Pattern · 51%","No Match · 0%"].map(x=><div className="border border-[#ccd8e5] p-3" key={x}>{x}</div>)}</div> : stage==="Investigation Context" ? <dl className="grid gap-3 sm:grid-cols-2"><div><dt className="text-[11px] text-[#66798d]">EVENT</dt><dd>{demoScenario.event}</dd></div><div><dt className="text-[11px] text-[#66798d]">RUNTIME DATASET</dt><dd>{demoScenario.dataset}</dd></div><div><dt className="text-[11px] text-[#66798d]">ALIGNED SURFACES</dt><dd>LiDAR / Ethernet / ROS / Power / Timing</dd></div><div><dt className="text-[11px] text-[#66798d]">ROBOT</dt><dd>{demoScenario.robot}</dd></div></dl> : stage==="Tier Candidate" ? <p>Investigation Tier Candidate · Tier 3 / Sensor Collaboration Candidate<br/>候选分层仅用于路由，不构成责任或根因判定。</p> : <p className="font-mono">{demoScenario.engagementPack}<br/>Evidence Pack ref: {demoScenario.evidencePack}<br/>Shared scope: LiDAR link / Ethernet timing / power summary</p>}
 </ArtifactCard><ArtifactCard title="Artifact control" status="DRAFT"><ul className="space-y-3"><li>artifact · {stage}</li><li>status · Pending human review</li><li>owner · OEM Engineering</li><li>boundary · OEM-controlled evidence</li></ul></ArtifactCard></div></AtlasDemoShell>;
}
