"use client";
import { useState } from "react";
import type { DemoContent } from "@/lib/content-types";
import { ArtifactCard, AtlasDemoShell, LifecycleRail, PageHeading, ScenarioStrip } from "@/components/demo/AtlasDemo";
const metrics=[
 ["Investigation volume","42 REF"],["Median investigation cycle","4.2 days"],["SLA","91%"],["Evidence coverage","86%"],
 ["Historical RGA reuse rate","67%"],["Repeated runtime-boundary patterns","12"],["Sensor collaboration turnaround","2.1 days"],["Assist Vault growth","+18 authorized assets"],
 ["Illustrative engineering hours saved","1,260 h"],["Illustrative ROI","¥252K"],
];
export default function CTODemoClient({content}:{content:DemoContent}){void content;const [range,setRange]=useState("90 days");return <AtlasDemoShell role="CTO / 工程副总裁"><PageHeading eyebrow="ENGINEERING GOVERNANCE" title="工程运营与调查治理仪表板" description="管理层只查看治理与工程运营指标；不展示未经授权的根因或责任结论。所有数值均为演示估算。"/><ScenarioStrip/><div className="mt-6"><LifecycleRail active="OEM Closure"/></div><div className="mt-6 flex flex-wrap gap-3">{["30 days","90 days","180 days"].map(x=><button onClick={()=>setRange(x)} className={`min-h-11 border px-4 ${range===x?"bg-[#1667b1] text-white":"bg-white"}`} key={x}>{x}</button>)}{["产品线 · All","OEM · Demo Robotics","传感器 · All"].map(x=><select aria-label={x} className="min-h-11 border bg-white px-3" key={x}><option>{x}</option></select>)}</div>
 <p className="mt-4 border-l-4 border-[#e1b72c] bg-[#fff7d6] p-3 font-semibold">演示估算 · {range} · 非客户实际结果</p><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-5">{metrics.map(([k,v],i)=><section className="border border-[#ccd8e5] bg-white p-5" key={k}><p className="min-h-10 text-[12px] text-[#52667c]">{k}</p><p className="mt-3 text-[24px] font-semibold text-[#092849]">{v}</p><p className="mt-2 text-[11px] text-[#8a6500]">演示估算</p>{i<8&&<div className="mt-4 h-2 bg-[#e2e9f0]"><div className="h-full bg-[#287ac1]" style={{width:`${45+i*6}%`}}/></div>}</section>)}</div>
 <div className="mt-5 grid gap-5 lg:grid-cols-2"><ArtifactCard title="治理边界" status="HUMAN GOVERNANCE" boundary="不显示未经授权的根因或责任结论。"><ul className="space-y-2"><li>OEM Closure 由授权人员完成</li><li>Assist Candidate 经审核后方可进入 Assist Vault</li><li>Historical RGA 仅表示复用与召回，不表示自动结论</li></ul></ArtifactCard><ArtifactCard title="Repeated runtime-boundary patterns" status="演示估算"><div className="space-y-3">{[["LiDAR / Ethernet timing",72],["Power stability",48],["ROS Topic latency",36]].map(([x,n])=><div key={x as string}><div className="flex justify-between"><span>{x}</span><span>{n}%</span></div><div className="mt-1 h-2 bg-[#e2e9f0]"><div className="h-full bg-[#287ac1]" style={{width:`${n}%`}}/></div></div>)}</div></ArtifactCard></div></AtlasDemoShell>}
