"use client";
import { useState } from "react";
import type { DemoContent } from "@/lib/content-types";
import { ArtifactCard, AtlasDemoShell, LifecycleRail, PageHeading, ScenarioStrip } from "@/components/demo/AtlasDemo";
import { demoScenario } from "@/data/demo/scenario";
export default function SensorFaeDemoClient({content}:{content:DemoContent}){void content;const [ir,setIr]=useState("Pending");return <AtlasDemoShell role="Sensor FAE / Alice Demo"><PageHeading eyebrow="SENSOR INVESTIGATION WORKSPACE" title="传感器制造商 FAE 调查工作区" description="接收 OEM 授权的 Sensor Engagement Pack™（传感器协作包），在明确的数据边界内返回调查结果。"/><ScenarioStrip/><div className="mt-6"><LifecycleRail active="Sensor Engagement"/></div><div className="mt-6 grid gap-5 xl:grid-cols-2">
 <ArtifactCard title={`Sensor Engagement Pack · ${demoScenario.engagementPack}`} status="AUTHORIZED" owner="Alice Demo / Example Sensor Corp" boundary="OEM 仅共享 LiDAR link、Ethernet timing 与必要电源摘要；完整机器人日志仍归 OEM。"><dl className="grid gap-4 sm:grid-cols-2"><I k="Sensor model / Runtime Profile" v="Example LiDAR X32 / RP-X32-DEMO-01"/><I k="Evidence Pack reference" v={demoScenario.evidencePack}/><I k="Investigation Context" v="LiDAR link interruption at canonical T0"/><I k="Tier Candidate" v="Tier 3 / Sensor collaboration"/></dl><h3 className="mt-5 text-[16px] font-semibold">Questions for Sensor FAE</h3><ol className="mt-2 list-decimal space-y-2 pl-5"><li>链路重置是否匹配已知 runtime profile 边界？</li><li>请评估固件、线缆与 EMI 候选路径。</li></ol></ArtifactCard>
 <ArtifactCard title="数据边界" status="OEM CONTROLLED"><div className="grid gap-3 sm:grid-cols-2"><div className="border border-[#ccd8e5] p-3"><b>OEM 可见 / 持有</b><p className="mt-2">完整 Runtime Dataset、REF、Closure、Assist 授权</p></div><div className="border border-[#ccd8e5] p-3"><b>传感器厂可见 / 提交</b><p className="mt-2">授权 EP 摘要、问题、Sensor IR / LL</p></div></div></ArtifactCard>
 <ArtifactCard title="Sensor IR · Investigation Result" status={ir} boundary="未经 OEM 授权的 IR 不得进入 Assist Vault。"><label className="text-[11px] font-bold">STATUS<select value={ir} onChange={e=>setIr(e.target.value)} className="mt-2 block min-h-11 w-full border p-3 text-[13px] font-normal"><option>Pending</option><option>Draft</option><option>Authorized</option></select></label><textarea aria-label="Sensor IR" className="mt-4 min-h-28 w-full border p-3" defaultValue="候选调查路径：复核链路完整性与 EMI 暴露；不构成根因确认。"/></ArtifactCard>
 <ArtifactCard title="Sensor LL · Lessons Learned / OEM Response" status="DRAFT" boundary="未经授权的 IR / LL 不写入 Assist Vault；OEM Response 决定后续验证与关闭。"><textarea aria-label="Sensor LL" className="min-h-24 w-full border p-3" defaultValue="Draft LL：在相同 runtime profile 下复测屏蔽线缆。"/><p className="mt-4"><b>OEM Response · Pending</b><br/>等待 OEM 工程师验证候选路径与共享范围。</p></ArtifactCard></div></AtlasDemoShell>};
function I({k,v}:{k:string;v:string}){return <div><dt className="text-[11px] text-[#66798d]">{k}</dt><dd className="mt-1 break-all font-medium">{v}</dd></div>}
