import type { DemoContent } from "@/lib/content-types";

export const demoContent = {
  index: {
    pages: [
      {
        id: "01",
        role: "一级支持",
        title: "客户门户",
        description:
          "快速创建 REF 并确认运行时数据集可用性。演示 4 步工作流：事件描述、机器人信息、运行时证据、审核路由。",
        href: "/demo/tier1",
        audience: "一线支持团队",
      },
      {
        id: "02",
        role: "二级/三级工程师",
        title: "调查仪表板",
        description:
          "将长运行时数据集归约为候选证据包。包含候选时间线、五窗口视图、历史 RGA 召回、EGP 生成器。",
        href: "/demo/investigation",
        audience: "OEM 工程团队",
      },
      {
        id: "03",
        role: "传感器 FAE",
        title: "传感器 FAE 工作区",
        description:
          "验证 OEM EGP、审查共享证据上下文、召回历史传感器 RGA、编写 IR / LL，返回传感器响应。",
        href: "/demo/sensor-fae",
        audience: "传感器厂商工程师",
      },
      {
        id: "04",
        role: "CTO / 工程副总裁",
        title: "管理层仪表板",
        description:
          "调查运营效率、证据覆盖率、组织记忆、供应商协作和示意性 ROI 的执行视图。",
        href: "/demo/cto",
        audience: "工程管理层",
      },
    ],
    hero: {
      eyebrow: "Atlas 演示界面",
      title: "四个角色演示界面",
      description:
        "通过一个连贯的客户故事，展示 Atlas 如何为不同角色提供运行时调查支持。所有演示使用共享静态数据。",
    },
    scenario: {
      eyebrow: "演示场景",
      title: "演示场景：Demo Robotics 导航偏差调查",
      customer: "客户",
      robotSerialNumber: "机器人序列号",
      refId: "REF 标识",
      primaryEvidencePack: "主要 Evidence Pack",
      egpId: "EGP 标识",
      sensorFae: "传感器 FAE",
    },
    viewDemo: "查看演示",
    notice: {
      label: "注意",
      description:
        "所有演示数据均为示意性内容。实际部署的 Atlas 界面包含客户特定的运行时上下文和调查资产，不会在公开演示中展示。",
      metrics:
        "商业指标（工时节省、成本节省）为演示估算值，不代表具体客户的实际结果。",
    },
    cta: {
      eyebrow: "申请完整演示",
      title: "需要完整的 Atlas 演示？",
      description:
        "联系我们安排定制化演示，包含您的实际运行时场景和调查工作流。",
      button: "联系我们",
    },
  },
  data: {
    customerName: "Demo Robotics",
    ref: {
      creatorName: "Zhang Ming (Demo)",
      incidentType: "导航偏差",
      severity: "中",
      description:
        "机器人在配送任务期间偏离规划路径。客户报告路线意外变化并延迟 3 分钟。",
      environmentLocation: "示例科技园区 A 座",
      environmentConditions: "室内，正常照明，中等人流",
      assignedToName: "Li Hua (Test)",
      sensorFaeName: "Alice Demo",
      sensorFaeVendor: "Example Sensor Corp",
    },
    robot: {
      model: "T300 Demo 配送型",
      lidarManufacturer: "Example Sensor Corp",
      lidarModel: "Example LiDAR X32",
    },
    evidencePack: {
      surface: "USB 总线时序",
      evidenceQuality: "权威",
      affectedSurfaces: [
        "USB 总线时序",
        "LiDAR 点云质量",
        "ROS2 主题时序",
      ],
      fiveWindowSummary: {
        pre_guard: "USB 总线运行正常，平均延迟 1.2ms",
        baseline: "USB 3.0 连接稳定，链路速度保持 5Gbps",
        deviation: "08:15:22.347 检测到 USB 总线重置，连接中断 4.8 秒",
        recovery: "USB 设备重新枚举完成，LiDAR 数据流恢复",
        post_guard: "连接稳定，未观察到进一步异常",
      },
      upstream: "电源稳定，未发生热事件",
      downstream: "导航模块进入降级模式，触发路径重新规划",
    },
    candidates: [
      {
        surface: "LiDAR 点云质量",
        description: "观察到 8:15:20-8:15:28 期间点云密度明显下降",
      },
      {
        surface: "ROS2 主题时序",
        description: "定位主题发布频率从 20Hz 降至 7Hz",
      },
      {
        surface: "USB 总线时序",
        description: "在 LiDAR 接口检测到 USB 3.0 总线重置",
      },
      {
        surface: "电源电压",
        description: "12V 电源轨出现轻微电压波动",
      },
    ],
    historicalRga: [
      {
        surface: "USB 总线时序",
        pattern: "高带宽传感器运行期间出现 USB 3.0 总线重置",
        resolution: "确认 USB 线缆存在 EMI 敏感性。更换屏蔽线缆并增加磁芯。",
        whyRetrieved: "模式匹配：USB 总线重置 + LiDAR 数据中断 + 导航降级",
        environmentDifference: "机器人不同，传感器型号相同，部署地点不同",
      },
      {
        surface: "电源电压",
        pattern: "12V 电源轨波动与 USB 设备重置相关",
        resolution: "电源电容老化。在预防性维护中更换电源。",
        whyRetrieved: "电源波动与 USB 重置存在时间相关性",
        environmentDifference: "机器人更旧（2024 年部署），运行时长更高",
      },
      {
        surface: "ROS2 主题时序",
        pattern: "定位主题频率下降，但未发现传感器硬件故障",
        resolution: "高负载期间 CPU 降频。改善散热并调整任务优先级。",
        whyRetrieved: "症状相似（主题频率下降），但机器人型号不同",
        environmentDifference: "型号不同（T200 与 T300），计算平台不同",
      },
    ],
  },
  cto: {
    roiModeLabels: {
      conservative: "保守",
      expected: "预期",
      actual: "实际",
    },
    dashboardTitle: "管理层仪表板",
    dashboardRole: "管理层",
    timeRangeLabel: "时间范围：",
    daySuffix: " 天",
    roiModelLabel: "ROI 模型：",
    operationsEyebrow: "调查运营效率",
    openRefsLabel: "开放 REF",
    openRefsTrend: "↓ 18%，较上一周期",
    safetyRefsLabel: "安全相关 REF",
    safetyRefsNote: "需要管理层审核",
    firstEvidencePackLabel: "首次 EP 中位用时",
    firstEvidencePackTrend: "↓ 12 分钟，较目标",
    closureLabel: "结案中位用时",
    closureTrend: "↓ 35%，较人工流程",
    memoryEyebrow: "组织记忆",
    memoryTitle: "历史 RGA 复用与供应商协作",
    reuseRateLabel: "历史 RGA 复用率",
    recallAfterRange: " 天：召回 ",
    recallAfterCount: " 个案例",
    escalationRateLabel: "传感器升级率",
    sentPrefix: "已发送 ",
    sentSuffix: " 个 EGP",
    activeSuppliersLabel: "活跃传感器供应商",
    activeSuppliers:
      "Example Sensor Corp, Demo Vision Systems, Example Motion Labs, Demo LiDAR Co, Test Optics",
    roiEyebrow: "示意性演示数据",
    roiTitle: "示意性 ROI 估算",
    hoursSavedLabel: "节省工程工时",
    basedOnPrefix: "基于",
    modelSeparator: "模型，",
    windowSuffix: " 天窗口",
    manualAverageLabel: "人工调查平均用时：",
    atlasAverageLabel: "Atlas 辅助平均用时：",
    savedPerRefLabel: "每个 REF 节省时间：",
    costSavedLabel: "预计节省成本",
    hourlyCostLabel: "工程师时薪：",
    totalHoursLabel: "节省总工时：",
    totalCostLabel: "节省成本：",
    roiNoticeLabel: "示意性演示数据：",
    roiNotice:
      "商业指标为演示估算值，不代表具体客户的实际结果。实际 ROI 取决于调查复杂度、团队效率和运营环境。",
    coverageEyebrow: "证据覆盖率",
    coverageTitle: "候选表面频率分布",
    surfaces: [
      "USB 总线时序",
      "ROS2 主题时序",
      "LiDAR 点云质量",
      "电源电压",
      "网络丢包",
      "存储 I/O 时序",
    ],
    occurrenceSuffix: " 次出现",
    noteLabel: "注意：",
    coverageNote:
      "候选表面频率表示观察到的模式分布，不代表根本原因排名或故障责任归属。",
    volumeEyebrow: "调查数量",
    volumeTitle: "REF 数量与状态趋势",
    months: ["4月", "5月", "6月", "7月"],
    closedRefsLabel: "已结案 REF",
    openChartLabel: "开放：",
    closedChartLabel: "已结案：",
    actionsEyebrow: "管理层操作",
    actionsTitle: "报告与审核",
    exportReportTitle: "导出治理报告",
    exportReportDescription:
      "包含调查效率、证据覆盖、组织记忆和供应商协作的执行摘要",
    reviewSafetyTitle: "审核安全相关 REF",
    reviewSafetyPrefix: "当前 ",
    reviewSafetySuffix: " 个安全相关 REF 需要执行审核",
    demoLabel: "演示",
    demoDescription:
      "实际 CTO 仪表板包含完整的多客户/车队过滤、自定义时间范围、可导出治理报告和实时 SLA 追踪。",
  },
  investigation: {
    confidenceLabels: {
      strong: "强候选",
      partial: "部分候选",
      related: "相关候选",
    },
    windowLabels: {
      pre_guard: "前置保护",
      baseline: "基线",
      deviation: "偏差",
      recovery: "恢复观察",
      post_guard: "后置保护",
    },
    statusLabels: {
      baseline: "基线",
      normal: "正常",
      anomaly_detected: "检测到异常",
      timing_anomaly: "时序异常",
      bus_reset: "总线重置",
      returning_to_baseline: "返回基线",
      partial_recovery: "部分恢复",
      reconnection: "重新连接",
      minor_fluctuation: "轻微波动",
      recovered: "已恢复",
      stable: "稳定",
    },
    dashboardTitle: "调查仪表板",
    robotLabel: "机器人",
    statusLabel: "状态",
    investigatingLabel: "调查中",
    generateEgp: "生成 EGP →",
    metricsEyebrow: "调查关键指标",
    candidatesIdentifiedLabel: "已识别候选",
    primaryEvidencePackLabel: "主要 EP",
    historicalRecallLabel: "历史召回",
    timeToFirstEvidencePackLabel: "首次 EP 用时",
    timelineEyebrow: "候选时间线",
    timelineTitle: "观察到的候选模式",
    primaryCandidateLabel: "主要候选",
    fiveWindowEyebrow: "五窗口证据模型",
    historicalEyebrow: "历史 RGA 召回",
    historicalTitle: "相关历史模式",
    relatedHistoricalLabel: "相关历史模式",
    whyRetrievedLabel: "为何召回：",
    environmentDifferenceLabel: "环境差异：",
    historicalResolutionLabel: "历史解决方案：",
    similarityLabel: "相似度",
    noteLabel: "注意：",
    historicalNote:
      "历史模式相似性不表明根本原因相同。环境差异可能导致不同的调查路径。",
    languageEyebrow: "措辞规范",
    languageTitle: "调查语言规范",
    prohibitedLabel: "禁用术语",
    prohibitedTerms: ["已确认根本原因", "OEM 故障", "传感器故障", "已分配责任"],
    allowedLabel: "允许术语",
    allowedTerms: [
      "观察到的模式",
      "候选表面",
      "强候选 / 部分候选",
      "相关历史模式",
      "需要进一步调查",
    ],
    demoLabel: "演示",
    demoDescription:
      "实际调查仪表板包含完整的候选操作（设为主要候选、延后、忽略）、EGP 生成器、SLA 追踪和团队协作功能。",
  },
  sensorFae: {
    irStatusLabels: {
      matched_known_pattern: "匹配已知模式",
      matched_with_mitigation: "匹配并完成缓解",
      candidate_investigation_path: "候选调查路径",
      candidate_field_test: "需要候选现场测试",
      not_applicable: "不适用于此传感器",
    },
    initialLessonLearned:
      "在高带宽 LiDAR 数据传输期间观察到 USB 3.0 总线重置。该模式与 Example LiDAR X32 演示线缆组件的 EMI 敏感性相匹配。建议的缓解措施：更换屏蔽线缆（P/N：DEMO-CBL-X32-SH），并在设备端增加磁芯。",
    workspaceTitle: "传感器 FAE 工作区",
    sensorLabel: "传感器",
    packageValidLabel: "包有效",
    validationEyebrow: "EGP 包验证",
    validationTitle: "包完整性检查",
    evidencePackIdLabel: "Evidence Pack 标识",
    evidenceQualityLabel: "证据质量",
    packageIntegrityLabel: "包完整性",
    verifiedLabel: "已验证",
    monitoredSurfacesLabel: "包含的监控表面",
    evidenceSummaryEyebrow: "Evidence Pack 摘要",
    deviationWindowLabel: "偏差窗口",
    upstreamContextLabel: "上游上下文",
    downstreamContextLabel: "下游上下文",
    historicalEyebrow: "历史 Sensor RGA",
    historicalTitle: "Example Sensor Corp 历史调查模式",
    strongCandidateLabel: "强候选",
    relatedHistoricalLabel: "相关历史模式",
    originalRefLabel: "原始 REF：",
    historicalResolutionLabel: "历史解决方案：",
    similarityLabel: "相似度",
    resultEyebrow: "调查结果（IR）",
    resultTitle: "编写调查结果",
    resultStatusLabel: "结果状态",
    resultSummaryLabel: "IR 摘要（演示）",
    resultSummaryPrefix: "与 ",
    resultSummarySuffix:
      " 的模式匹配已确认。高带宽运行期间出现的 USB 3.0 总线重置与 Example LiDAR X32 线缆的演示 EMI 敏感性一致。未发现固件或硬件缺陷。建议更换为屏蔽线缆。",
    lessonEyebrow: "经验教训（LL）",
    lessonTitle: "记录可复用知识",
    lessonContentLabel: "经验教训内容",
    lessonNote:
      "LL 将更新到 Example Sensor Corp Historical Sensor RGA，供未来调查使用。",
    responseEyebrow: "传感器响应",
    responseTitle: "返回 OEM 调查包",
    responseSummaryLabel: "响应摘要",
    irStatusLabel: "IR 状态",
    lessonAuthoredLabel: "LL 已撰写",
    yesLabel: "是",
    historicalUpdatedLabel: "Historical RGA 已更新",
    pendingLabel: "待处理",
    readyLabel: "准备返回 OEM",
    readyDescription:
      "IR 和 LL 将随 EGP 响应包返回到 OEM Tier 2/3 工程师，用于后续调查决策。",
    returnResponse: "返回 EGP 响应到 OEM →",
    demoLabel: "演示",
    demoDescription:
      "实际传感器 FAE 工作区包含完整的包验证、多传感器表面分析、IR/LL 模板库和传感器 RGA 更新工作流。",
  },
  tier1: {
    portalTitle: "一级支持门户",
    roleLabel: "一级支持",
    stepLabels: {
      incident: "事件描述",
      robot: "机器人信息",
      evidence: "运行时证据",
      review: "审核路由",
    },
    previous: "← 上一步",
    incident: {
      eyebrow: "步骤 1 / 4",
      title: "描述事件",
      typeLabel: "事件类型",
      typeOptions: ["传感器异常", "通信中断", "性能下降"],
      severityLabel: "严重程度",
      severityOptions: ["低", "高", "严重"],
      descriptionLabel: "事件描述",
      timeLabel: "事件时间（近似）",
      next: "下一步：机器人信息 →",
    },
    robot: {
      eyebrow: "步骤 2 / 4",
      title: "机器人与环境",
      serialNumberLabel: "机器人序列号",
      modelLabel: "型号",
      firmwareLabel: "固件版本",
      locationLabel: "部署位置",
      conditionsLabel: "环境条件",
      next: "下一步：运行时证据 →",
    },
    evidence: {
      eyebrow: "步骤 3 / 4",
      title: "运行时证据",
      agentStatusLabel: "Atlas Agent 状态",
      activeLabel: "活跃",
      versionLabel: "版本",
      heartbeatLabel: "最后心跳",
      timeWindowLabel: "运行时数据集时间窗口",
      durationLabel: "持续时间: 15 分钟",
      lockedLabel: "运行时数据集已锁定",
      datasetIdLabel: "运行时数据集 ID：",
      coverageLabel: "覆盖范围：时序、电源、网络、存储、传感器、ROS2 主题",
      next: "下一步：审核路由 →",
    },
    review: {
      eyebrow: "步骤 4 / 4",
      title: "审核并路由到 Tier 2",
      summaryLabel: "REF 摘要",
      incidentTypeLabel: "事件类型",
      severityLabel: "严重程度",
      robotLabel: "机器人",
      datasetLabel: "运行时数据集",
      routeToLabel: "路由到",
      routeOptions: [
        "二级工程师 - Li Hua (Test)",
        "二级工程师 - Chen Example",
        "三级专家",
      ],
      readyLabel: "准备创建 REF",
      readyDescription:
        "创建后将生成 REF ID 并路由到指定工程师。运行时数据集已锁定，可用于证据生成。",
      submit: "创建 REF 并路由 →",
    },
    demoLabel: "演示",
    demoDescription:
      "这是一个静态演示界面。实际一级支持门户将提交到 Atlas 后端并触发二级工作流。",
  },
} satisfies DemoContent;
