export const legacyZhCopy = {
  runtimeInvestigation: {
    text001: "Tier 1 记录客户报告、设备、环境、时间范围、事件类型和证据可用性。",
    text002: "将相关运行时数据整理为有边界、可引用、可验证的统一证据入口。",
    text003: "优先召回历史调查资产，并说明匹配特征、差异条件与 why retrieved。",
    text004: "将当前 REF、Evidence Pack、历史候选、已知缺口和调查问题放入同一上下文。",
    text005: "建议调查层级",
    text006: "建议进入 Tier 1、Tier 2、Tier 3 或 Sensor FAE 调查流程，由授权工程师确认。",
    text007: "OEM 工程师或 Sensor FAE 执行调查路径、补充证据、复现和工程评估。",
    text008: "工程师提交 Investigation Result 与 Lesson Learned，完成调查关闭条件。",
    text009: "将完成的调查沉淀为可检索、可比较、可复用的组织调查资产。",
    text010: "统一证据入口",
    text011: "调查不再直接从海量原始日志开始。Atlas 使用 Evidence Pack™ 组织时间线、运行时 Surface、事件标记、完整性信息与原始证据引用。",
    text012: "历史调查召回",
    text013: "每一次 REF 优先检索 Historical RGA™。支持强匹配、部分匹配和弱匹配，并保留 why retrieved，避免工程团队重新从零开始。",
    text014: "统一调查上下文",
    text015: "将当前事件、五段证据窗口、异常现象、历史候选、证据缺口和下一步调查问题组织在同一个 Investigation Context 中。",
    text016: "调查路由建议",
    text017: "根据当前证据与事件范围生成建议调查层级，帮助组织将事件路由至 Tier 1、Tier 2、Tier 3 或 Sensor FAE。",
    text018: "OEM 与 Sensor 协同",
    text019: "通过 Sensor Engagement Pack™（传感器协同调查包），让 OEM 与传感器制造商基于同一组证据、问题和数据边界开展调查。",
    text020: "调查资产复用",
    text021: "IR、LL、调查路径、排除路径和关闭记录被转化为 RGA，并进入 Assist Vault，供未来 REF 调查召回和复用。",
    text022: "记录事件、客户报告、时间范围、严重度和路由状态。",
    text023: "提供统一、受控、可引用的运行时调查证据入口。",
    text024: "记录历史候选、匹配等级、相同维度、差异维度和 why retrieved。",
    text025: "统一组织当前证据、历史资产、调查缺口与下一步问题。",
    text026: "为 Tier 1、Tier 2、Tier 3 或 Sensor FAE 提供路由建议。",
    text027: "支持 OEM 与 Sensor FAE 的标准化证据交换和调查协作。",
    text028: "保存工程调查结果、可复用经验和正式关闭记录。",
    text029: "将完成的调查转化为未来可以检索和复用的组织资产。",
    text030: "REF Intake 与 Admission Policy",
    text031: "Evidence Pack 引用与五段证据窗口",
    text032: "Historical RGA 强匹配、部分匹配与弱匹配召回",
    text033: "Why Retrieved 与匹配差异说明",
    text034: "RGA Generation、Assist Vault 与 Future REF Reuse",
    text035: "客户控制的数据所有权与交换边界",
    text036: "自动确认 Root Cause 或 Causality",
    text037: "自动判定 OEM Fault 或 Sensor Fault",
    text038: "执行 Liability Assignment",
    text039: "替代 Tier 2、Tier 3 工程师或 Sensor FAE",
    text040: "自动生成未经工程师确认的最终 IR 或 LL",
    text041: "将历史调查结论直接复制为当前结论",
    text042: "\n              机器人 OEM\n            ",
    text043: "\n              将一次 Runtime Execution Failure，从客户报告推进到统一证据、\n              历史召回、工程调查、调查关闭和未来复用。\n            ",
    text044: "\n              Atlas 帮助机器人 OEM 将运行时事件转化为有界\n              Evidence Pack™，创建和管理 REF 工单，召回 Historical\n              RGA™，协调 Tier 1、Tier 2、Tier 3 与 Sensor FAE，并将完成的\n              IR 与 LL 沉淀为组织调查资产。\n            ",
    text045: "\n                查看所有产品\n              ",
    text046: "\n                REF 描述运行时事件，\n                ",
    text047: "\n                不自动等同于根因。\n              ",
    text048: "\n                机器人突然停止、碰撞、漏障、定位失败或路径偏离，都可以成为\n                REF。事件可能同时涉及传感器、总线、电源、Linux Runtime、\n                驱动、ROS Topic 或应用行为。\n              ",
    text049: "\n                Atlas 组织证据和调查流程，但不在 REF 建立时自动确认根因、\n                因果关系或责任归属。\n              ",
    text050: "\n                从 REF Intake 到 Future REF Reuse\n              ",
    text051: "\n                Atlas 将零散的客户报告、运行时数据、历史经验和工程结果，\n                组织为一条可追踪、可关闭、可复用的标准调查链。\n              ",
    text052: "\n                当前调查从结构化证据开始。\n                ",
    text053: "\n                下一次调查，从组织记忆开始。\n              ",
    text054: "\n                  为机器人 OEM 建立标准化调查能力\n                ",
    text055: "\n                  Atlas 不替代现有日志、ROS2、驱动工具链或工程团队。\n                  它在这些系统之上，建立证据入口、历史召回、调查路由和资产复用层。\n                ",
    text056: "\n                Engagement Pack™（协同调查包）\n              ",
    text057: "\n                当 REF 涉及 Sensor Candidate 时，OEM 可以通过 Sensor\n                Engagement Pack™，将相关 Evidence Pack、调查上下文、\n                Sensor Surface、历史候选、问题清单与数据交换边界发送给\n                Sensor FAE。\n              ",
    text058: "\n                  在 OEM 授权情况下，Sensor FAE 可以查看指定的原始数据、\n                  Packet Capture、Frame、Point Cloud、Driver Log\n                  或运行时时间线引用。\n                ",
    text059: "\n                  当原始数据不能直接共享时，仅交换 Evidence Signature、\n                  Runtime Metadata、Timeline Summary、Surface Coverage、\n                  历史召回结果和调查问题。\n                ",
    text060: "\n                每一次完成的调查，\n                ",
    text061: "\n                都成为未来可以复用的组织资产\n              ",
    text062: "\n                  Atlas 负责组织证据、流程与调查资产\n                ",
    text063: "\n                  Atlas 不替代授权工程判断\n                ",
    text064: "\n                  历史资产用于辅助当前调查，不替代当前证据，也不自动将历史结论升格为本次确定结论。\n                ",
    text065: "\n                  建立运行时证据基础\n                ",
    text066: "\n                  将证据转化为调查与组织记忆\n                ",
    text067: "\n              Atlas 不替代工程师。\n              ",
    text068: "\n              Atlas 让工程师不再从零开始。\n            ",
    text069: "\n              让每一次 REF 从结构化证据和历史 RGA 开始，\n              让每一次完成的调查成为下一次可以复用的组织能力。\n            ",
    text070: "\n                查看 Runtime Sensor Governance\n              ",
  },
  runtimeSensorGovernance: {
    text001: "7×24 小时持续观察 Sensor、Bus、Power、Linux Runtime、Driver 与 ROS Topic 的运行状态。",
    text002: "将运行时元数据、时间戳、频率、连接状态、驱动事件与 Surface 状态持续写入 Runtime Dataset。",
    text003: "按照客户定义的 Retention Policy 管理数据时长、粒度、循环空间和事件前后窗口。",
    text004: "按照授权将运行时数据、Evidence Pack 和完整性清单导出至客户私有调查环境。",
    text005: "Tier 1 提供约莫 REF 时段",
    text006: "最终用户、客服或现场人员只需提供大约发生时间。Atlas 在 Runtime Dataset 中定位候选范围，并向前、向后扩展证据窗口。",
    text007: "客户电话报障",
    text008: "售后工单",
    text009: "人工观察到异常",
    text010: "没有明确机器触发事件",
    text011: "Atlas Agent 根据单一数据流异常或多个 Runtime Surface 的时间关联，自动建立候选事件中心点。",
    text012: "LiDAR Topic Frequency 归零",
    text013: "Driver 与 ROS Topic 同时停止",
    text014: "保留事件前较早阶段的运行状态，观察异常是否已经逐步形成。",
    text015: "建立事件前的正常参考，用于确认频率、连续性和连接状态。",
    text016: "记录主要异常出现和发展的阶段，并对齐多个 Runtime Surface。",
    text017: "记录系统恢复、重连、重启或持续失败的过程与顺序。",
    text018: "验证恢复是否稳定，并观察异常是否再次发生。",
    text019: "Atlas Agent 持续观察、持久化并按照保留策略管理的运行时数据基础。",
    text020: "围绕候选 REF 时段建立的 Pre-Guard、Baseline、Deviation、Recovery 和 Post-Guard 五段窗口。",
    text021: "面向具体 REF 的标准化运行时证据包，包含时间线、Surface Coverage、事件标记和证据引用。",
    text022: "将 Sensor、Bus、Linux、Driver 与 ROS Topic 对齐到统一时间轴。",
    text023: "说明本次 Evidence Pack 已覆盖和未覆盖的 Runtime Surface。",
    text024: "建议调查层级",
    text025: "根据证据完整度、事件范围和跨数据流关联，建议进入 Tier 1、Tier 2、Tier 3 或 Sensor FAE。",
    text026: "按照客户策略导出的调查数据、证据引用和完整性清单。",
    text027: "为后续 Historical RGA Recall、Investigation Context 和工程调查提供统一证据入口。",
    text028: "7×24 小时持续运行时观察",
    text029: "Runtime Dataset 持久化",
    text030: "Retention Policy 管理",
    text031: "客户授权下的数据导出",
    text032: "Tier 1 约莫 REF 时段切片",
    text033: "Dataset Abnormal 自动触发",
    text034: "Evidence Pack 生成",
    text035: "Runtime Timeline 对齐",
    text036: "OEM 私有环境部署",
    text037: "自动确认 Root Cause",
    text038: "自动确认因果关系",
    text039: "执行 Liability Assignment",
    text040: "替代 OEM 工程师或 Sensor FAE",
    text041: "SLAM、Navigation 或 Motion Planning 调试",
    text042: "AI Model 或 Robot Business Logic 调试",
    text043: "将运行时关联自动升格为工程结论",
    text044: "\n              为机器人传感器运行时边界建立持续观察、证据保留和事件窗口生成能力。\n            ",
    text045: "\n              Atlas 将 Sensor、Bus、Power、Linux Runtime、Driver 与 ROS\n              Topic 之间分散的运行时数据，组织为可保留、可导出、可调查的\n              Runtime Evidence，并在 REF 发生时生成标准化 Evidence Pack™。\n            ",
    text046: "\n                查看所有产品\n              ",
    text047: "\n                不是生成更多日志。\n                ",
    text048: "\n                是建立持续在线的运行时证据链。\n              ",
    text049: "\n                Atlas Agent 在机器人主控板或指定运行环境中持续运行，\n                将瞬时状态沉淀为可追踪的 Runtime Dataset，并按照客户策略进行保留和导出。\n              ",
    text050: "\n                  Atlas 持续观察传感器到主控系统之间的运行时边界\n                ",
    text051: "\n                  实际覆盖范围由部署配置、Surface Registry、可访问数据和客户数据策略决定。\n                ",
    text052: "\n                Atlas Agent 的目标不是立即判断根因，而是持续建立可保留、可引用和可导出的运行时事实记录。\n              ",
    text053: "\n                手动时段与自动检测，\n                ",
    text054: "\n                共同生成候选事件窗口\n              ",
    text055: "\n                Atlas 支持由 Tier 1 提供约莫 REF 时段，也支持根据 Runtime\n                Dataset 异常和跨数据流关联自动建立 Candidate Event Time。\n              ",
    text056: "\n                Candidate Event 和 Cross-stream Correlation 是调查入口，\n                不是 Root Cause、Causality 或 Liability 结论。\n              ",
    text057: "\n                不只截取异常瞬间，\n                ",
    text058: "\n                保留事件前、中、后的完整变化\n              ",
    text059: "\n                每个 Evidence Pack 按五段时间窗口组织，\n                为正常状态、异常发展、恢复过程和恢复稳定性提供统一证据上下文。\n              ",
    text060: "\n                从 Five-Window Evidence\n                ",
    text061: "\n                到建议调查层级\n              ",
    text062: "\n                Atlas 根据证据完整度、Runtime Surface 覆盖范围、\n                异常强度和跨数据流关联，生成调查路由建议。\n              ",
    text063: "继续补充客户报告、时间、设备和证据可用性。",
    text064: "进入标准 Evidence Pack 审查和工程调查路径。",
    text065: "升级至跨系统或专项工程调查。",
    text066: "生成 Sensor Engagement Pack 并进入传感器厂协同调查。",
    text067: "\n              建议调查层级是路由建议，不是根因结论。最终层级由客户组织的\n              Admission Policy 和授权工程师确认。\n            ",
    text068: "\n                从持续观察到标准 Evidence Pack\n              ",
    text069: "\n                Runtime Dataset 是持续运行的数据基础；Evidence Pack\n                是围绕特定 REF 生成的标准调查证据包。两者不是同一个对象。\n              ",
    text070: "\n                  Atlas 负责建立运行时证据基础\n                ",
    text071: "\n                  Atlas 不替代工程判断\n                ",
    text072: "\n                  Atlas 记录运行时事实、生成证据窗口并支持调查路由。\n                  最终工程结论由获得授权的客户工程团队完成。\n                ",
    text073: "\n                  建立运行时证据基础\n                ",
    text074: "\n                  Observe → Persist → Retain → Export → Evidence Pack → 建议调查层级\n                ",
    text075: "\n                  将证据转化为调查和组织记忆\n                ",
    text076: "\n              Atlas 不等待事故发生后，\n              ",
    text077: "\n              才开始寻找证据。\n            ",
    text078: "\n              让 Atlas Agent 持续观察、保留和导出运行时事实，\n              在 REF 发生时快速生成有边界、可追踪、可调查的 Evidence Pack。\n            ",
    text079: "\n                查看 Runtime Investigation\n              ",
  },
  demoIndex: {
    text001: "一级支持",
    text002: "客户门户",
    text003: "快速创建 REF 并确认运行时数据集可用性。演示 4 步工作流：事件描述、机器人信息、运行时证据、审核路由。",
    text004: "一线支持团队",
    text005: "二级/三级工程师",
    text006: "调查仪表板",
    text007: "将长运行时数据集归约为候选证据包。包含候选时间线、五窗口视图、历史 RGA 召回、EGP 生成器。",
    text008: "OEM 工程团队",
    text009: "传感器 FAE",
    text010: "传感器 FAE 工作区",
    text011: "验证 OEM EGP、审查共享证据上下文、召回历史传感器 RGA、编写 IR / LL，返回传感器响应。",
    text012: "传感器厂商工程师",
    text013: "CTO / 工程副总裁",
    text014: "管理层仪表板",
    text015: "调查运营效率、证据覆盖率、组织记忆、供应商协作和示意性 ROI 的执行视图。",
    text016: "工程管理层",
    text017: "Atlas 演示界面",
    text018: "\n              四个角色演示界面\n            ",
    text019: "\n              通过一个连贯的客户故事，展示 Atlas\n              如何为不同角色提供运行时调查支持。所有演示使用共享静态数据。\n            ",
    text020: "演示场景",
    text021: "\n              演示场景：Demo Robotics 导航偏差调查\n            ",
    text022: "客户",
    text023: "机器人序列号",
    text024: "REF 标识",
    text025: "\n                  主要 Evidence Pack\n                ",
    text026: "EGP 标识",
    text027: "\n                    申请演示\n                    ",
    text028: "\n                注意\n              ",
    text029: "\n                  所有演示数据均为示意性内容。实际部署的 Atlas\n                  界面包含客户特定的运行时上下文和调查资产，不会在公开演示中展示。\n                ",
    text030: "\n                  商业指标（工时节省、成本节省）为演示估算值，不代表具体客户的实际结果。\n                ",
    text031: "申请完整演示",
    text032: "\n                  需要完整的 Atlas 演示？\n                ",
    text033: "\n                  联系我们安排定制化演示，包含您的实际运行时场景和调查工作流。\n                ",
    text034: "\n                  联系我们\n                  ",
  },
  demoCto: {
    text001: "保守",
    text002: "预期",
    text003: "实际",
    text004: "管理层仪表板",
    text005: "\n                管理层\n              ",
    text006: "时间范围：",
    text007: " 天\n                  ",
    text008: "ROI 模型：",
    text009: "调查运营效率",
    text010: "开放 REF",
    text011: "↓ 18%，较上一周期",
    text012: "安全相关 REF",
    text013: "需要管理层审核",
    text014: "首次 EP 中位用时",
    text015: "↓ 12 分钟，较目标",
    text016: "结案中位用时",
    text017: "↓ 35%，较人工流程",
    text018: "组织记忆",
    text019: "\n            历史 RGA 复用与供应商协作\n          ",
    text020: "历史 RGA 复用率",
    text021: " 天：召回 ",
    text022: " 个案例\n              ",
    text023: "传感器升级率",
    text024: "\n                已发送 ",
    text025: " 个 EGP\n              ",
    text026: "活跃传感器供应商",
    text027: "示意性演示数据",
    text028: "\n            示意性 ROI 估算\n          ",
    text029: "节省工程工时",
    text030: "\n                基于",
    text031: "模型，",
    text032: " 天窗口\n              ",
    text033: "人工调查平均用时：",
    text034: "Atlas 辅助平均用时：",
    text035: "每个 REF 节省时间：",
    text036: "预计节省成本",
    text037: "工程师时薪：",
    text038: "节省总工时：",
    text039: "节省成本：",
    text040: "示意性演示数据：",
    text041: "\n              商业指标为演示估算值，不代表具体客户的实际结果。实际 ROI\n              取决于调查复杂度、团队效率和运营环境。\n            ",
    text042: "证据覆盖率",
    text043: "\n            候选表面频率分布\n          ",
    text044: "USB 总线时序",
    text045: "ROS2 主题时序",
    text046: "LiDAR 点云质量",
    text047: "电源电压",
    text048: "网络丢包",
    text049: "存储 I/O 时序",
    text050: " 次出现",
    text051: "注意：",
    text052: "\n              候选表面频率表示观察到的模式分布，不代表根本原因排名或故障责任归属。\n            ",
    text053: "调查数量",
    text054: "\n            REF 数量与状态趋势\n          ",
    text055: "4月",
    text056: "5月",
    text057: "6月",
    text058: "7月",
    text059: "已结案 REF",
    text060: "管理层操作",
    text061: "\n            报告与审核\n          ",
    text062: "导出治理报告",
    text063: "\n                包含调查效率、证据覆盖、组织记忆和供应商协作的执行摘要\n              ",
    text064: "审核安全相关 REF",
    text065: "\n                当前 ",
    text066: " 个安全相关 REF 需要执行审核\n              ",
    text067: "\n                演示\n              ",
    text068: "\n                实际 CTO 仪表板\n                包含完整的多客户/车队过滤、自定义时间范围、可导出治理报告和实时 SLA 追踪。\n              ",
    text069: "开放：",
    text070: "已结案：",
  },
  demoInvestigation: {
    text001: "强候选",
    text002: "部分候选",
    text003: "相关候选",
    text004: "前置保护",
    text005: "基线",
    text006: "偏差",
    text007: "恢复观察",
    text008: "后置保护",
    text009: "调查仪表板",
    text010: "机器人",
    text011: "状态",
    text012: "调查中",
    text013: "\n              生成 EGP →\n            ",
    text014: "调查关键指标",
    text015: "已识别候选",
    text016: "主要 EP",
    text017: "历史召回",
    text018: "首次 EP 用时",
    text019: "候选时间线",
    text020: "观察到的候选模式",
    text021: "\n                          主要候选\n                        ",
    text022: "五窗口证据模型",
    text023: "正常",
    text024: "检测到异常",
    text025: "时序异常",
    text026: "总线重置",
    text027: "返回基线",
    text028: "部分恢复",
    text029: "重新连接",
    text030: "轻微波动",
    text031: "已恢复",
    text032: "稳定",
    text033: "历史 RGA 召回",
    text034: "相关历史模式",
    text035: "为何召回：",
    text036: "环境差异：",
    text037: "历史解决方案：",
    text038: "相似度",
    text039: "注意：",
    text040: "\n              历史模式相似性不表明根本原因相同。环境差异可能导致不同的调查路径。\n            ",
    text041: "措辞规范",
    text042: "\n            调查语言规范\n          ",
    text043: "❌ 禁用术语",
    text044: "已确认根本原因",
    text045: "OEM 故障",
    text046: "传感器故障",
    text047: "已分配责任",
    text048: "✓ 允许术语",
    text049: "观察到的模式",
    text050: "候选表面",
    text051: "强候选 / 部分候选",
    text052: "需要进一步调查",
    text053: "演示",
    text054: "\n                实际调查仪表板包含完整的候选操作（设为主要候选、延后、忽略）、EGP\n                生成器、SLA 追踪和团队协作功能。\n              ",
  },
  demoSensorFae: {
    text001: "匹配已知模式",
    text002: "匹配并完成缓解",
    text003: "候选调查路径",
    text004: "需要候选现场测试",
    text005: "不适用于此传感器",
    text006: "在高带宽 LiDAR 数据传输期间观察到 USB 3.0 总线重置。该模式与 Example LiDAR X32 演示线缆组件的 EMI 敏感性相匹配。建议的缓解措施：更换屏蔽线缆（P/N：DEMO-CBL-X32-SH），并在设备端增加磁芯。",
    text007: "传感器 FAE 工作区",
    text008: "传感器",
    text009: "\n              包有效\n            ",
    text010: "EGP 包验证",
    text011: "包完整性检查",
    text012: "Evidence Pack 标识",
    text013: "证据质量",
    text014: "包完整性",
    text015: "已验证",
    text016: "\n             包含的监控表面\n            ",
    text017: "Evidence Pack 摘要",
    text018: "\n                偏差窗口\n              ",
    text019: "\n                上游上下文\n              ",
    text020: "\n                下游上下文\n              ",
    text021: "历史 Sensor RGA",
    text022: "\n            Example Sensor Corp 历史调查模式\n          ",
    text023: "强候选",
    text024: "相关历史模式",
    text025: "原始 REF：",
    text026: "历史解决方案：",
    text027: "相似度",
    text028: "调查结果（IR）",
    text029: "编写调查结果",
    text030: "结果状态",
    text031: "\n                  候选调查路径\n                ",
    text032: "\n                IR 摘要（演示）\n              ",
    text033: "\n                与 ",
    text034: " 的模式匹配已确认。高带宽运行期间出现的 USB 3.0 总线重置与 Example LiDAR X32 线缆的演示 EMI 敏感性一致。未发现固件或硬件缺陷。建议更换为屏蔽线缆。\n              ",
    text035: "经验教训（LL）",
    text036: "\n            记录可复用知识\n          ",
    text037: "经验教训内容",
    text038: "\n              LL 将更新到 Example Sensor Corp Historical Sensor RGA，供未来调查使用。\n            ",
    text039: "传感器响应",
    text040: "\n            返回 OEM 调查包\n          ",
    text041: "\n                响应摘要\n              ",
    text042: "IR 状态",
    text043: "LL 已撰写",
    text044: "是",
    text045: "Historical RGA 已更新",
    text046: "待处理",
    text047: "\n                准备返回 OEM\n              ",
    text048: "\n                IR 和 LL 将随 EGP 响应包返回到 OEM Tier 2/3 工程师，用于后续调查决策。\n              ",
    text049: "\n              返回 EGP 响应到 OEM →\n            ",
    text050: "\n                演示\n              ",
    text051: "\n                实际传感器 FAE 工作区包含完整的包验证、多传感器表面分析、IR/LL\n                模板库和传感器 RGA 更新工作流。\n              ",
  },
  demoTier1: {
    text001: "一级支持门户",
    text002: "\n                一级支持\n              ",
    text003: "事件描述",
    text004: "机器人信息",
    text005: "运行时证据",
    text006: "审核路由",
    text007: "步骤 1 / 4",
    text008: "\n                描述事件\n              ",
    text009: "\n                    事件类型\n                  ",
    text010: "传感器异常",
    text011: "通信中断",
    text012: "性能下降",
    text013: "\n                    严重程度\n                  ",
    text014: "低",
    text015: "高",
    text016: "严重",
    text017: "\n                    事件描述\n                  ",
    text018: "\n                    事件时间（近似）\n                  ",
    text019: "\n                下一步：机器人信息 →\n              ",
    text020: "步骤 2 / 4",
    text021: "\n                机器人与环境\n              ",
    text022: "\n                    机器人序列号\n                  ",
    text023: "\n                      型号\n                    ",
    text024: "\n                      固件版本\n                    ",
    text025: "\n                    部署位置\n                  ",
    text026: "\n                    环境条件\n                  ",
    text027: "\n                  ← 上一步\n                ",
    text028: "\n                  下一步：运行时证据 →\n                ",
    text029: "步骤 3 / 4",
    text030: "\n                运行时证据\n              ",
    text031: "\n                        Atlas Agent 状态\n                      ",
    text032: "\n                      活跃\n                    ",
    text033: "版本",
    text034: "最后心跳",
    text035: "\n                    运行时数据集时间窗口\n                  ",
    text036: "\n                    持续时间: 15 分钟\n                  ",
    text037: "\n                    运行时数据集已锁定\n                  ",
    text038: "\n                    运行时数据集 ID：",
    text039: "\n                    覆盖范围：时序、电源、网络、存储、传感器、ROS2 主题\n                  ",
    text040: "\n                  下一步：审核路由 →\n                ",
    text041: "步骤 4 / 4",
    text042: "\n                审核并路由到 Tier 2\n              ",
    text043: "REF 摘要",
    text044: "事件类型",
    text045: "严重程度",
    text046: "机器人",
    text047: "运行时数据集",
    text048: "\n                    路由到\n                  ",
    text049: "二级工程师 - Li Hua (Test)",
    text050: "二级工程师 - Chen Example",
    text051: "三级专家",
    text052: "\n                    准备创建 REF\n                  ",
    text053: "\n                    创建后将生成 REF ID 并路由到指定工程师。运行时数据集已锁定，可用于证据生成。\n                  ",
    text054: "\n                  创建 REF 并路由 →\n                ",
    text055: "\n                演示\n              ",
    text056: "\n                这是一个静态演示界面。实际一级支持门户将提交到 Atlas 后端并触发二级工作流。\n              ",
  },
} as const;
