export const legacyZhCopy = {
  runtimeInvestigation: {
    ui: {
      heroEyebrow: "机器人 OEM",
      heroTitle: "Atlas 运行时调查™",
      runtimeFailureEyebrow: "运行时执行故障",
      standardChainEyebrow: "标准调查链",
      coreCapabilitiesEyebrow: "核心能力",
      collaborationEyebrow: "OEM ↔ 传感器制造商",
      investigationAssetsEyebrow: "调查资产",
      atlasSupportsEyebrow: "Atlas 支持",
      constitutionalBoundaryEyebrow: "原则边界",
      governanceProductName: "运行时传感器治理™",
      investigationProductName: "运行时调查™",
      finalEyebrow: "从证据到组织记忆",
      viewAllProducts: "查看所有产品",
      flowTitles: [
        "REF 接入",
        "Evidence Pack",
        "Historical RGA 召回",
        "调查上下文",
        "建议调查层级",
        "工程调查",
        "IR · LL · 关闭",
        "RGA · Assist Vault · 复用",
      ],
      refExamples: [
        "意外停止",
        "碰撞",
        "障碍物漏检",
        "障碍物误检",
        "定位失败",
        "路径偏离",
        "跌倒",
        "操作失败",
      ],
      outputTitles: [
        "REF 工单",
        "Evidence Pack™",
        "Historical RGA 匹配结果",
        "调查上下文",
        "建议调查层级",
        "Sensor Engagement Pack™",
        "IR · LL · 关闭",
        "RGA · Assist Vault",
      ],
      supportItems: [
        "调查上下文",
        "建议调查层级",
        "OEM Tier 1 / Tier 2 / Tier 3 工作流",
        "传感器制造商 FAE 工作流",
        "Sensor Engagement Pack 模式 A / 模式 B",
        "IR / LL / 关闭资产管理",
      ],
      collaborationSteps: [
        "OEM REF",
        "Evidence Pack",
        "协同调查包",
        "传感器 REF",
        "传感器 IR / LL",
        "OEM 关闭",
      ],
      exchangeModeA: "交换模式 A",
      exchangeModeB: "交换模式 B",
      rawEvidenceReference: "原始证据引用",
      signatureAndRecall: "签名与召回",
      governanceFlow: "观察 → 持久化 → 保留 → 导出 → Evidence Pack",
      investigationFlow:
        "召回 → 上下文 → 调查 → IR / LL → 关闭 → RGA → 复用",
    },
    text001: "Tier 1 记录客户报告、设备、环境、时间范围、事件类型和证据可用性。",
    text002: "将相关运行时数据整理为有边界、可引用、可验证的统一证据入口。",
    text003: "优先召回历史调查资产，并说明匹配特征、差异条件与 why retrieved。",
    text004: "将当前 REF、Evidence Pack、历史候选、已知缺口和调查问题放入同一上下文。",
    text005: "建议调查层级",
    text006: "建议进入 Tier 1、Tier 2、Tier 3 或 Sensor FAE 调查流程，由授权工程师确认。",
    text007: "OEM 工程师或 Sensor FAE 执行调查路径、补充证据、复现和工程评估。",
    text008: "工程师提交 Investigation Result 与 Lesson Learned，完成调查关闭条件。",
    text009: "将完成的调查沉淀为可检索、可比较、可复用的组织调查资产。",
    text010: "统一证据入口",
    text011: "调查不再直接从海量原始日志开始。Atlas 使用 Evidence Pack™ 组织时间线、运行时 Surface、事件标记、完整性信息与原始证据引用。",
    text012: "历史调查召回",
    text013: "每一次 REF 优先检索 Historical RGA™。支持强匹配、部分匹配和弱匹配，并保留 why retrieved，避免工程团队重新从零开始。",
    text014: "统一调查上下文",
    text015: "将当前事件、五段证据窗口、异常现象、历史候选、证据缺口和下一步调查问题组织在同一个 Investigation Context 中。",
    text016: "调查路由建议",
    text017: "根据当前证据与事件范围生成建议调查层级，帮助组织将事件路由至 Tier 1、Tier 2、Tier 3 或 Sensor FAE。",
    text018: "OEM 与 Sensor 协同",
    text019: "通过 Sensor Engagement Pack™（传感器协同调查包），让 OEM 与传感器制造商基于同一组证据、问题和数据边界开展调查。",
    text020: "调查资产复用",
    text021: "IR、LL、调查路径、排除路径和关闭记录被转化为 RGA，并进入 Assist Vault，供未来 REF 调查召回和复用。",
    text022: "记录事件、客户报告、时间范围、严重度和路由状态。",
    text023: "提供统一、受控、可引用的运行时调查证据入口。",
    text024: "记录历史候选、匹配等级、相同维度、差异维度和 why retrieved。",
    text025: "统一组织当前证据、历史资产、调查缺口与下一步问题。",
    text026: "为 Tier 1、Tier 2、Tier 3 或 Sensor FAE 提供路由建议。",
    text027: "支持 OEM 与 Sensor FAE 的标准化证据交换和调查协作。",
    text028: "保存工程调查结果、可复用经验和正式关闭记录。",
    text029: "将完成的调查转化为未来可以检索和复用的组织资产。",
    text030: "REF Intake 与 Admission Policy",
    text031: "Evidence Pack 引用与五段证据窗口",
    text032: "Historical RGA 强匹配、部分匹配与弱匹配召回",
    text033: "Why Retrieved 与匹配差异说明",
    text034: "RGA Generation、Assist Vault 与 Future REF Reuse",
    text035: "客户控制的数据所有权与交换边界",
    text036: "自动确认 Root Cause 或 Causality",
    text037: "自动判定 OEM Fault 或 Sensor Fault",
    text038: "执行 Liability Assignment",
    text039: "替代 Tier 2、Tier 3 工程师或 Sensor FAE",
    text040: "自动生成未经工程师确认的最终 IR 或 LL",
    text041: "将历史调查结论直接复制为当前结论",
    text042: "\n              机器人 OEM\n            ",
    text043: "\n              将一次 Runtime Execution Failure，从客户报告推进到统一证据、\n              历史召回、工程调查、调查关闭和未来复用。\n            ",
    text044: "\n              Atlas 帮助机器人 OEM 将运行时事件转化为有界\n              Evidence Pack™，创建和管理 REF 工单，召回 Historical\n              RGA™，协调 Tier 1、Tier 2、Tier 3 与 Sensor FAE，并将完成的\n              IR 与 LL 沉淀为组织调查资产。\n            ",
    text045: "\n                查看所有产品\n              ",
    text046: "\n                REF 描述运行时事件，\n                ",
    text047: "\n                不自动等同于根因。\n              ",
    text048: "\n                机器人突然停止、碰撞、漏障、定位失败或路径偏离，都可以成为\n                REF。事件可能同时涉及传感器、总线、电源、Linux Runtime、\n                驱动、ROS Topic 或应用行为。\n              ",
    text049: "\n                Atlas 组织证据和调查流程，但不在 REF 建立时自动确认根因、\n                因果关系或责任归属。\n              ",
    text050: "\n                从 REF Intake 到 Future REF Reuse\n              ",
    text051: "\n                Atlas 将零散的客户报告、运行时数据、历史经验和工程结果，\n                组织为一条可追踪、可关闭、可复用的标准调查链。\n              ",
    text052: "\n                当前调查从结构化证据开始。\n                ",
    text053: "\n                下一次调查，从组织记忆开始。\n              ",
    text054: "\n                  为机器人 OEM 建立标准化调查能力\n                ",
    text055: "\n                  Atlas 不替代现有日志、ROS2、驱动工具链或工程团队。\n                  它在这些系统之上，建立证据入口、历史召回、调查路由和资产复用层。\n                ",
    text056: "\n                Engagement Pack™（协同调查包）\n              ",
    text057: "\n                当 REF 涉及 Sensor Candidate 时，OEM 可以通过 Sensor\n                Engagement Pack™，将相关 Evidence Pack、调查上下文、\n                Sensor Surface、历史候选、问题清单与数据交换边界发送给\n                Sensor FAE。\n              ",
    text058: "\n                  在 OEM 授权情况下，Sensor FAE 可以查看指定的原始数据、\n                  Packet Capture、Frame、Point Cloud、Driver Log\n                  或运行时时间线引用。\n                ",
    text059: "\n                  当原始数据不能直接共享时，仅交换 Evidence Signature、\n                  Runtime Metadata、Timeline Summary、Surface Coverage、\n                  历史召回结果和调查问题。\n                ",
    text060: "\n                每一次完成的调查，\n                ",
    text061: "\n                都成为未来可以复用的组织资产\n              ",
    text062: "\n                  Atlas 负责组织证据、流程与调查资产\n                ",
    text063: "\n                  Atlas 不替代授权工程判断\n                ",
    text064: "\n                  历史资产用于辅助当前调查，不替代当前证据，也不自动将历史结论升格为本次确定结论。\n                ",
    text065: "\n                  建立运行时证据基础\n                ",
    text066: "\n                  将证据转化为调查与组织记忆\n                ",
    text067: "\n              Atlas 不替代工程师。\n              ",
    text068: "\n              Atlas 让工程师不再从零开始。\n            ",
    text069: "\n              让每一次 REF 从结构化证据和历史 RGA 开始，\n              让每一次完成的调查成为下一次可以复用的组织能力。\n            ",
    text070: "\n                查看 Runtime Sensor Governance\n              ",
  },
  runtimeSensorGovernance: {
    ui: {
      heroEyebrow: "传感器运行时边界",
      heroTitle: "Atlas 运行时传感器治理™",
      runtimeEvidenceChainEyebrow: "运行时证据链",
      runtimeBoundaryEyebrow: "运行时边界",
      atlasAgentEyebrow: "Atlas Agent",
      agentChainTitle: "观察 → 持久化 → 保留 → 导出",
      evidencePackGenerationEyebrow: "Evidence Pack 生成",
      fiveWindowModelEyebrow: "五段证据窗口模型",
      investigationRoutingEyebrow: "调查路由",
      runtimeEvidenceAssetsEyebrow: "运行时证据资产",
      atlasSupportsEyebrow: "Atlas 支持",
      constitutionalBoundaryEyebrow: "原则边界",
      governanceProductName: "运行时传感器治理™",
      investigationProductName: "运行时调查™",
      continuousEvidenceEyebrow: "持续运行时证据",
      viewAllProducts: "查看所有产品",
      capabilityTitles: ["观察", "持久化", "保留", "导出"],
      eventModeLabels: ["手动事件窗口", "自动检测"],
      automaticEventTitle: "数据集异常 + 跨数据流关联",
      automaticEventExamples: ["摄像头帧中断", "USB / 以太网断连"],
      evidenceWindowTitles: ["前置保护", "基线", "偏差", "恢复", "后置保护"],
      runtimeSurfaces: [
        "摄像头",
        "LiDAR",
        "IMU",
        "GNSS",
        "USB",
        "以太网",
        "CAN",
        "电源",
        "时序 / PPS",
        "Linux 运行时",
        "驱动运行时",
        "ROS Topic",
      ],
      runtimeBoundaryPath:
        "物理传感器 → 原始输出 → 电源 / 总线 → Linux 内核 / 驱动 → ROS Topic / 应用回调",
      outputTitles: [
        "Runtime Dataset™",
        "证据窗口",
        "Evidence Pack™",
        "运行时时间线",
        "Surface 覆盖快照",
        "建议调查层级",
        "导出包",
        "调查入口",
      ],
      supportItems: [
        "跨数据流关联",
        "五段证据窗口模型",
        "Runtime Surface 覆盖",
      ],
      tierTitles: ["Tier 1", "Tier 2", "Tier 3", "Sensor FAE"],
      governanceFlow:
        "观察 → 持久化 → 保留 → 导出 → Evidence Pack → 建议调查层级",
      investigationFlow:
        "REF 接入 → Historical RGA → 上下文 → IR / LL → 关闭 → Assist Vault",
    },
    text001: "7×24 小时持续观察 Sensor、Bus、Power、Linux Runtime、Driver 与 ROS Topic 的运行状态。",
    text002: "将运行时元数据、时间戳、频率、连接状态、驱动事件与 Surface 状态持续写入 Runtime Dataset。",
    text003: "按照客户定义的 Retention Policy 管理数据时长、粒度、循环空间和事件前后窗口。",
    text004: "按照授权将运行时数据、Evidence Pack 和完整性清单导出至客户私有调查环境。",
    text005: "Tier 1 提供约莫 REF 时段",
    text006: "最终用户、客服或现场人员只需提供大约发生时间。Atlas 在 Runtime Dataset 中定位候选范围，并向前、向后扩展证据窗口。",
    text007: "客户电话报障",
    text008: "售后工单",
    text009: "人工观察到异常",
    text010: "没有明确机器触发事件",
    text011: "Atlas Agent 根据单一数据流异常或多个 Runtime Surface 的时间关联，自动建立候选事件中心点。",
    text012: "LiDAR Topic Frequency 归零",
    text013: "Driver 与 ROS Topic 同时停止",
    text014: "保留事件前较早阶段的运行状态，观察异常是否已经逐步形成。",
    text015: "建立事件前的正常参考，用于确认频率、连续性和连接状态。",
    text016: "记录主要异常出现和发展的阶段，并对齐多个 Runtime Surface。",
    text017: "记录系统恢复、重连、重启或持续失败的过程与顺序。",
    text018: "验证恢复是否稳定，并观察异常是否再次发生。",
    text019: "Atlas Agent 持续观察、持久化并按照保留策略管理的运行时数据基础。",
    text020: "围绕候选 REF 时段建立的 Pre-Guard、Baseline、Deviation、Recovery 和 Post-Guard 五段窗口。",
    text021: "面向具体 REF 的标准化运行时证据包，包含时间线、Surface Coverage、事件标记和证据引用。",
    text022: "将 Sensor、Bus、Linux、Driver 与 ROS Topic 对齐到统一时间轴。",
    text023: "说明本次 Evidence Pack 已覆盖和未覆盖的 Runtime Surface。",
    text024: "建议调查层级",
    text025: "根据证据完整度、事件范围和跨数据流关联，建议进入 Tier 1、Tier 2、Tier 3 或 Sensor FAE。",
    text026: "按照客户策略导出的调查数据、证据引用和完整性清单。",
    text027: "为后续 Historical RGA Recall、Investigation Context 和工程调查提供统一证据入口。",
    text028: "7×24 小时持续运行时观察",
    text029: "Runtime Dataset 持久化",
    text030: "Retention Policy 管理",
    text031: "客户授权下的数据导出",
    text032: "Tier 1 约莫 REF 时段切片",
    text033: "Dataset Abnormal 自动触发",
    text034: "Evidence Pack 生成",
    text035: "Runtime Timeline 对齐",
    text036: "OEM 私有环境部署",
    text037: "自动确认 Root Cause",
    text038: "自动确认因果关系",
    text039: "执行 Liability Assignment",
    text040: "替代 OEM 工程师或 Sensor FAE",
    text041: "SLAM、Navigation 或 Motion Planning 调试",
    text042: "AI Model 或 Robot Business Logic 调试",
    text043: "将运行时关联自动升格为工程结论",
    text044: "\n              为机器人传感器运行时边界建立持续观察、证据保留和事件窗口生成能力。\n            ",
    text045: "\n              Atlas 将 Sensor、Bus、Power、Linux Runtime、Driver 与 ROS\n              Topic 之间分散的运行时数据，组织为可保留、可导出、可调查的\n              Runtime Evidence，并在 REF 发生时生成标准化 Evidence Pack™。\n            ",
    text046: "\n                查看所有产品\n              ",
    text047: "\n                不是生成更多日志。\n                ",
    text048: "\n                是建立持续在线的运行时证据链。\n              ",
    text049: "\n                Atlas Agent 在机器人主控板或指定运行环境中持续运行，\n                将瞬时状态沉淀为可追踪的 Runtime Dataset，并按照客户策略进行保留和导出。\n              ",
    text050: "\n                  Atlas 持续观察传感器到主控系统之间的运行时边界\n                ",
    text051: "\n                  实际覆盖范围由部署配置、Surface Registry、可访问数据和客户数据策略决定。\n                ",
    text052: "\n                Atlas Agent 的目标不是立即判断根因，而是持续建立可保留、可引用和可导出的运行时事实记录。\n              ",
    text053: "\n                手动时段与自动检测，\n                ",
    text054: "\n                共同生成候选事件窗口\n              ",
    text055: "\n                Atlas 支持由 Tier 1 提供约莫 REF 时段，也支持根据 Runtime\n                Dataset 异常和跨数据流关联自动建立 Candidate Event Time。\n              ",
    text056: "\n                Candidate Event 和 Cross-stream Correlation 是调查入口，\n                不是 Root Cause、Causality 或 Liability 结论。\n              ",
    text057: "\n                不只截取异常瞬间，\n                ",
    text058: "\n                保留事件前、中、后的完整变化\n              ",
    text059: "\n                每个 Evidence Pack 按五段时间窗口组织，\n                为正常状态、异常发展、恢复过程和恢复稳定性提供统一证据上下文。\n              ",
    text060: "\n                从 Five-Window Evidence\n                ",
    text061: "\n                到建议调查层级\n              ",
    text062: "\n                Atlas 根据证据完整度、Runtime Surface 覆盖范围、\n                异常强度和跨数据流关联，生成调查路由建议。\n              ",
    text063: "继续补充客户报告、时间、设备和证据可用性。",
    text064: "进入标准 Evidence Pack 审查和工程调查路径。",
    text065: "升级至跨系统或专项工程调查。",
    text066: "生成 Sensor Engagement Pack 并进入传感器厂协同调查。",
    text067: "\n              建议调查层级是路由建议，不是根因结论。最终层级由客户组织的\n              Admission Policy 和授权工程师确认。\n            ",
    text068: "\n                从持续观察到标准 Evidence Pack\n              ",
    text069: "\n                Runtime Dataset 是持续运行的数据基础；Evidence Pack\n                是围绕特定 REF 生成的标准调查证据包。两者不是同一个对象。\n              ",
    text070: "\n                  Atlas 负责建立运行时证据基础\n                ",
    text071: "\n                  Atlas 不替代工程判断\n                ",
    text072: "\n                  Atlas 记录运行时事实、生成证据窗口并支持调查路由。\n                  最终工程结论由获得授权的客户工程团队完成。\n                ",
    text073: "\n                  建立运行时证据基础\n                ",
    text074: "\n                  Observe → Persist → Retain → Export → Evidence Pack → 建议调查层级\n                ",
    text075: "\n                  将证据转化为调查和组织记忆\n                ",
    text076: "\n              Atlas 不等待事故发生后，\n              ",
    text077: "\n              才开始寻找证据。\n            ",
    text078: "\n              让 Atlas Agent 持续观察、保留和导出运行时事实，\n              在 REF 发生时快速生成有边界、可追踪、可调查的 Evidence Pack。\n            ",
    text079: "\n                查看 Runtime Investigation\n              ",
  },
} as const;
